### ISSUE TITLE
Net::Whois::Object throwing fatal error handling Verisign response

### ISSUE THREAD

**Issue by hashbangperl** [arhuman/Net-Whois-RIPE#27]
Querying  with ip query 8.8.8.8 using the code snippet below causes fatal "Unrecognized Object" error.

`
my $whois = Net::Whois::RIPE->new( hostname => 'whois.verisign-grs.com', port => 43, recursive => 1 );
my $iterator = $whois->query('8.8.8.8');
my @objects = Net::Whois::Object->new($iterator);
`

Previously the old version of Net::Whois::RIPE worked:
`
while ( my $query = $iterator->next ) {
  my $attr = [ $query->attributes ];
 ...
}
`

I've added a failing test in a branch of my fork : https://github.com/hashbangperl/Net-Whois-RIPE/blob/verisign_errors/t/05-more-objects.t

Are we using the API in the wrong way, or is this no longer supported functionality?

Thanks!

Aaron

**Comment by arhuman** [comment]
Seems like whois.verisign-grs.com doesn't use the RIPE database format.
If you really need it and points me to the right documentation I could implement their format.

Can you tell me why you have to use verisign instead of:
my $whois = Net::Whois::RIPE->new( );
my $iterator = $whois->query('8.8.8.8'); 
my @objects = Net::Whois::Object->new($iterator);
